export default [
	{
		url:"/home",
		name:"Home",
		icon:"mdi-home",
	},
	{
		url:"/starter-page",
		name:"StarterPage",
		icon:"mdi-home-export-outline",
	},
	{
		url:"/login",
		name:"Login",
		icon:"mdi-login",
	},
	{
		url:"/register",
		name:"Register",
		icon:"mdi-cellphone-link",
	},
	{
		url:"/tutorials",
		name:"Tutorials",
		icon:"mdi-clipboard-text",
	},
	{
		url:"/users",
		name:"Users",
		icon:"mdi-account-group",
	},
	{
		url:"/roles",
		name:"Roles",
		icon:"mdi-shield-account",
	},
	{
		url:"/analytics",
		name:"Analytics",
		icon:"mdi-chart-areaspline",
	},
	{
		url:"/page-not-found",
		name:"Page Not Found",
		icon:"mdi-alert-rhombus-outline",
	},

]